default: &default
  adapter: postgresql
  encoding: unicode
  # For details on how to build this configuration:
  # https://guides.rubyonrails.org/configuring.html#database-configuration
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 127.0.0.1
  port: 5433

development:
  <<: *default
  database: wonderful_editor_development

test:
  <<: *default
  database: wonderful_editor_test

production:
  <<: *default
  database: wonderful_editor_production
  password: <%= ENV['WONDERFUL_EDITOR_DATABASE_PASSWORD'] %>
